// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7jVBKgwveu_WNf_ZFvubwUZmVhpD0JL4',
    appId: '1:900211554320:web:706a8eaf8cd3c67dc9b295',
    messagingSenderId: '900211554320',
    projectId: 'dubai-fashion-6355a',
    authDomain: 'dubai-fashion-6355a.firebaseapp.com',
    storageBucket: 'dubai-fashion-6355a.firebasestorage.app',
    measurementId: 'G-1REQ1BZTGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCESs9jBB1hUD2JvAGoA95wVERY5n6wi3Y',
    appId: '1:900211554320:android:9ce649fef89cc2b7c9b295',
    messagingSenderId: '900211554320',
    projectId: 'dubai-fashion-6355a',
    storageBucket: 'dubai-fashion-6355a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj7ZNsqbLjjI72EQC5ZSP8Y38Zghvr6I4',
    appId: '1:900211554320:ios:f55dad1f23cdbc35c9b295',
    messagingSenderId: '900211554320',
    projectId: 'dubai-fashion-6355a',
    storageBucket: 'dubai-fashion-6355a.firebasestorage.app',
    iosBundleId: 'com.example.dubaiFashion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj7ZNsqbLjjI72EQC5ZSP8Y38Zghvr6I4',
    appId: '1:900211554320:ios:f55dad1f23cdbc35c9b295',
    messagingSenderId: '900211554320',
    projectId: 'dubai-fashion-6355a',
    storageBucket: 'dubai-fashion-6355a.firebasestorage.app',
    iosBundleId: 'com.example.dubaiFashion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7jVBKgwveu_WNf_ZFvubwUZmVhpD0JL4',
    appId: '1:900211554320:web:bed296bacea2d877c9b295',
    messagingSenderId: '900211554320',
    projectId: 'dubai-fashion-6355a',
    authDomain: 'dubai-fashion-6355a.firebaseapp.com',
    storageBucket: 'dubai-fashion-6355a.firebasestorage.app',
    measurementId: 'G-SMRT94F4EP',
  );

}